import React, { useState, useRef } from 'react';
import confetti from 'canvas-confetti';
import { useFinancials, EX_RATES, formatCurrency, vibrate } from '../context/FinancialContext';
import { 
  Download, UploadCloud, RefreshCw, CheckCircle2, AlertTriangle, 
  ShieldCheck, FileJson, FileSpreadsheet, X, ArrowRight, 
  Database, HardDrive, Check, Sparkles, Layers, ArrowUpRight
} from 'lucide-react';

export const DataBackupModal = ({ isOpen, onClose }) => {
  const { 
    wallets, 
    transactions, 
    budgets, 
    goals, 
    bills, 
    user, 
    exportFullBackupJSON, 
    importFullBackupJSON, 
    syncWithCloud, 
    exportCSV, 
    lastSyncedTime, 
    isSyncing,
    preferences
  } = useFinancials();

  const [activeTab, setActiveTab] = useState('export'); // 'export' | 'import'
  const [dragOver, setDragOver] = useState(false);
  const [fileError, setFileError] = useState(null);
  const [parsedBackup, setParsedBackup] = useState(null);
  const [backupAnalysis, setBackupAnalysis] = useState(null);
  const [importMode, setImportMode] = useState('merge'); // 'merge' | 'replace'
  const [isRestoring, setIsRestoring] = useState(false);
  const [restoreSuccess, setRestoreSuccess] = useState(null);

  const fileInputRef = useRef(null);

  if (!isOpen) return null;

  // Format relative time helper
  const formatLastSync = (isoString) => {
    if (!isoString) return 'Not yet synced';
    const diffSeconds = Math.max(0, Math.floor((Date.now() - new Date(isoString).getTime()) / 1000));
    if (diffSeconds < 45) return 'Just now';
    if (diffSeconds < 3600) return `${Math.floor(diffSeconds / 60)}m ago`;
    if (diffSeconds < 86400) return `${Math.floor(diffSeconds / 3600)}h ago`;
    return new Date(isoString).toLocaleDateString(undefined, { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' });
  };

  // Analyze uploaded backup structure
  const analyzeBackupData = (data) => {
    if (!data || typeof data !== 'object') {
      throw new Error("Invalid backup file: Expected a JSON object.");
    }

    const txList = Array.isArray(data.transactions) ? data.transactions : [];
    const walletsList = Array.isArray(data.wallets) ? data.wallets : [];
    const budgetsList = Array.isArray(data.budgets) ? data.budgets : [];
    const goalsList = Array.isArray(data.goals) ? data.goals : [];
    const billsList = Array.isArray(data.bills) ? data.bills : [];
    const backupCurr = data.preferences?.baseCurrency || data.metadata?.baseCurrency || data.baseCurrency || 'INR';

    // Must have at least something recognizable
    if (txList.length === 0 && walletsList.length === 0 && budgetsList.length === 0 && goalsList.length === 0) {
      throw new Error("Empty backup: No transactions, wallets, or budgets found in file.");
    }

    // Determine date range of transactions
    let dateRange = 'No transactions';
    if (txList.length > 0) {
      const timestamps = txList
        .map(t => new Date(t.date).getTime())
        .filter(t => !isNaN(t))
        .sort((a, b) => a - b);

      if (timestamps.length > 0) {
        const minDate = new Date(timestamps[0]);
        const maxDate = new Date(timestamps[timestamps.length - 1]);
        const fmt = (d) => d.toLocaleString('en-US', { month: 'short', year: 'numeric' });
        const startStr = fmt(minDate);
        const endStr = fmt(maxDate);
        dateRange = startStr === endStr ? startStr : `${startStr} – ${endStr}`;
      }
    }

    // Compute net worth inside backup
    let netWorth = 0;
    const baseRate = EX_RATES[backupCurr] || 1;
    txList.forEach(t => {
      const w = walletsList.find(w => String(w.id) === String(t.walletId));
      const wCurr = w?.currency || backupCurr;
      const rate = EX_RATES[wCurr] || 1;
      const converted = (Number(t.amount || 0) * rate) / baseRate;
      if (t.type === 'income') netWorth += converted;
      if (t.type === 'expense') netWorth -= converted;
    });

    return {
      version: data.metadata?.version || data.version || '3.0',
      exportedAt: data.metadata?.exportedAt || data.exportedAt || null,
      currency: backupCurr,
      walletsCount: walletsList.length,
      txCount: txList.length,
      budgetsAndGoalsCount: budgetsList.length + goalsList.length,
      billsCount: billsList.length,
      dateRange,
      netWorth
    };
  };

  const processFile = (file) => {
    setFileError(null);
    setRestoreSuccess(null);

    if (!file) return;
    if (!file.name.endsWith('.json') && file.type !== 'application/json') {
      setFileError("Please select a valid .json file generated by Cashly.");
      vibrate('warning');
      return;
    }

    const reader = new FileReader();
    reader.onload = (event) => {
      try {
        const json = JSON.parse(event.target.result);
        const analysis = analyzeBackupData(json);
        setParsedBackup(json);
        setBackupAnalysis(analysis);
        vibrate('success');
      } catch (err) {
        console.error("Backup parse error:", err);
        setFileError(err.message || "Unable to read backup file. Please ensure it is valid Cashly JSON.");
        setParsedBackup(null);
        setBackupAnalysis(null);
        vibrate('warning');
      }
    };
    reader.onerror = () => {
      setFileError("Failed to read file from disk.");
      vibrate('warning');
    };
    reader.readAsText(file);
  };

  const handleDrop = (e) => {
    e.preventDefault();
    setDragOver(false);
    if (e.dataTransfer.files && e.dataTransfer.files.length > 0) {
      processFile(e.dataTransfer.files[0]);
    }
  };

  const handleFileSelect = (e) => {
    if (e.target.files && e.target.files.length > 0) {
      processFile(e.target.files[0]);
    }
  };

  const handleRestoreNow = async () => {
    if (!parsedBackup) return;
    vibrate('medium');
    setIsRestoring(true);
    setFileError(null);

    try {
      const res = await importFullBackupJSON(parsedBackup, importMode);
      if (res && res.success) {
        confetti({
          particleCount: 70,
          spread: 75,
          origin: { y: 0.65 }
        });
        vibrate('success');
        setRestoreSuccess({
          mode: importMode,
          importedCounts: res.importedCounts || res.stats || {
            transactions: backupAnalysis?.txCount || 0,
            wallets: backupAnalysis?.walletsCount || 0
          }
        });
      } else {
        setFileError(res?.error || "Restore process failed.");
        vibrate('warning');
      }
    } catch (err) {
      console.error("Restore error:", err);
      setFileError(err.message || "Failed to restore ledger.");
      vibrate('warning');
    } finally {
      setIsRestoring(false);
    }
  };

  const handleResetImport = () => {
    vibrate('light');
    setParsedBackup(null);
    setBackupAnalysis(null);
    setFileError(null);
    setRestoreSuccess(null);
    if (fileInputRef.current) {
      fileInputRef.current.value = '';
    }
  };

  return (
    <div className="fixed inset-0 z-[100] flex flex-col justify-end pointer-events-none font-sans">
      {/* Dark Blur Backdrop */}
      <div 
        className="absolute inset-0 bg-black/80 backdrop-blur-md pointer-events-auto transition-opacity duration-300"
        onClick={onClose}
      />

      {/* Modal Content Sheet */}
      <div className="bg-[#1C1C1E]/95 backdrop-blur-2xl w-full max-h-[90vh] overflow-y-auto rounded-t-[2.5rem] p-6 pb-10 pointer-events-auto animate-spring-up border-t border-white/10 text-white space-y-5 relative z-[101] shadow-2xl no-scrollbar">
        
        {/* Header Bar */}
        <div className="flex items-center justify-between pb-3 border-b border-gray-800/80">
          <div className="flex items-center gap-2.5">
            <div className="w-9 h-9 rounded-2xl bg-emerald-500/20 text-emerald-400 flex items-center justify-center border border-emerald-500/30 shadow-inner">
              <Database className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-lg font-extrabold text-white tracking-tight flex items-center gap-2">
                Backup & Restore
              </h2>
              <p className="text-[11px] font-medium text-gray-400">
                100% Zero-Loss Ledger Portability & Cloud Sync
              </p>
            </div>
          </div>

          <button 
            onClick={() => { vibrate('light'); onClose(); }}
            className="w-8 h-8 rounded-full bg-white/10 hover:bg-white/20 text-gray-300 hover:text-white flex items-center justify-center transition-all active:scale-90"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Tab Navigation Pill Selector */}
        <div className="flex p-1 bg-[#2C2C2E]/80 rounded-2xl border border-gray-800">
          <button
            onClick={() => { vibrate('light'); setActiveTab('export'); }}
            className={`flex-1 py-2.5 rounded-xl font-extrabold text-xs flex items-center justify-center gap-2 transition-all ${
              activeTab === 'export'
                ? 'bg-emerald-500 text-white shadow-lg shadow-emerald-500/25'
                : 'text-gray-400 hover:text-gray-200'
            }`}
          >
            <Download className="w-3.5 h-3.5" />
            Export Ledger
          </button>

          <button
            onClick={() => { vibrate('light'); setActiveTab('import'); }}
            className={`flex-1 py-2.5 rounded-xl font-extrabold text-xs flex items-center justify-center gap-2 transition-all ${
              activeTab === 'import'
                ? 'bg-emerald-500 text-white shadow-lg shadow-emerald-500/25'
                : 'text-gray-400 hover:text-gray-200'
            }`}
          >
            <UploadCloud className="w-3.5 h-3.5" />
            Restore & Import
          </button>
        </div>

        {/* ======================= EXPORT TAB ======================= */}
        {activeTab === 'export' && (
          <div className="space-y-4 animate-fade-in">
            {/* Big Hero Card: Full Ledger JSON Backup */}
            <div className="bg-gradient-to-br from-emerald-950/60 via-[#1F2723] to-[#161B18] rounded-3xl p-5 border border-emerald-500/40 shadow-xl space-y-4 relative overflow-hidden group">
              <div className="absolute top-0 right-0 w-36 h-36 bg-emerald-500/10 rounded-full blur-3xl pointer-events-none" />
              
              <div className="flex items-start justify-between relative z-10">
                <div className="flex items-center gap-3">
                  <div className="w-12 h-12 rounded-2xl bg-emerald-500/20 text-emerald-400 border border-emerald-500/30 flex items-center justify-center shadow-inner group-hover:scale-105 transition-transform">
                    <FileJson className="w-6 h-6" />
                  </div>
                  <div>
                    <div className="flex items-center gap-2">
                      <h3 className="font-extrabold text-base text-white">Full Ledger Backup</h3>
                      <span className="px-2 py-0.5 rounded-full bg-emerald-500/20 text-emerald-400 text-[10px] font-extrabold border border-emerald-500/30 tracking-wider">
                        JSON
                      </span>
                    </div>
                    <p className="text-xs text-gray-300 font-medium mt-0.5">
                      Backs up all accounts, full transaction history, budgets, and savings jars with 100% zero data loss.
                    </p>
                  </div>
                </div>
              </div>

              {/* Current Ledger Summary Chips */}
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 pt-1 relative z-10">
                <div className="bg-black/40 rounded-xl p-2.5 border border-white/5 text-center">
                  <p className="text-[10px] uppercase font-bold text-gray-400">💼 Accounts</p>
                  <p className="text-sm font-extrabold text-white mt-0.5">{wallets.length}</p>
                </div>
                <div className="bg-black/40 rounded-xl p-2.5 border border-white/5 text-center">
                  <p className="text-[10px] uppercase font-bold text-gray-400">📝 Records</p>
                  <p className="text-sm font-extrabold text-white mt-0.5">{transactions.length}</p>
                </div>
                <div className="bg-black/40 rounded-xl p-2.5 border border-white/5 text-center">
                  <p className="text-[10px] uppercase font-bold text-gray-400">🎯 Goals & Jars</p>
                  <p className="text-sm font-extrabold text-white mt-0.5">{budgets.length + goals.length}</p>
                </div>
                <div className="bg-black/40 rounded-xl p-2.5 border border-white/5 text-center">
                  <p className="text-[10px] uppercase font-bold text-gray-400">🧾 Bills</p>
                  <p className="text-sm font-extrabold text-white mt-0.5">{bills.length}</p>
                </div>
              </div>

              {/* Download JSON Button */}
              <button
                onClick={() => {
                  vibrate('success');
                  exportFullBackupJSON();
                }}
                className="w-full py-3.5 px-4 rounded-2xl bg-emerald-500 hover:bg-emerald-400 text-black font-black text-xs shadow-lg shadow-emerald-500/30 flex items-center justify-center gap-2 transition-all active:scale-98 cursor-pointer relative z-10"
              >
                <Download className="w-4 h-4 text-black stroke-[2.5]" />
                Export Full Ledger Backup (JSON)
              </button>
            </div>

            {/* Secondary Option: Spreadsheet CSV */}
            <div className="bg-[#242426]/70 rounded-3xl p-4 border border-gray-800 flex items-center justify-between gap-4 hover:border-gray-700 transition-colors">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-2xl bg-blue-500/10 text-blue-400 border border-blue-500/20 flex items-center justify-center">
                  <FileSpreadsheet className="w-5 h-5" />
                </div>
                <div>
                  <h4 className="font-bold text-sm text-white">Export CSV (Spreadsheet)</h4>
                  <p className="text-xs text-gray-400">Tabular format for Excel, Apple Numbers, or Google Sheets</p>
                </div>
              </div>

              <button
                onClick={() => {
                  vibrate('medium');
                  exportCSV();
                }}
                className="py-2.5 px-4 rounded-xl bg-gray-800 hover:bg-gray-700 text-gray-200 font-bold text-xs border border-gray-700 active:scale-95 transition-all flex items-center gap-1.5 whitespace-nowrap"
              >
                <Download className="w-3.5 h-3.5" />
                Export CSV
              </button>
            </div>

            {/* Google Cloud Sync Status Card */}
            <div className="bg-[#19191B] rounded-3xl p-4 border border-white/5 space-y-3">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2.5">
                  <div className={`w-2.5 h-2.5 rounded-full ${user ? 'bg-emerald-400 shadow-[0_0_8px_#34d399]' : 'bg-gray-500'}`} />
                  <div>
                    <span className="text-xs font-bold text-gray-300">Google Cloud Sync</span>
                    <p className="text-[10px] text-gray-500">
                      {user ? `Connected as ${user.email}` : 'Sign in to enable continuous cloud replication'}
                    </p>
                  </div>
                </div>

                {user && (
                  <span className="text-[10px] font-mono text-gray-400">
                    {formatLastSync(lastSyncedTime)}
                  </span>
                )}
              </div>

              {user && (
                <button
                  onClick={syncWithCloud}
                  disabled={isSyncing}
                  className="w-full py-2.5 rounded-xl bg-white/5 hover:bg-white/10 text-emerald-400 font-extrabold text-xs border border-emerald-500/20 flex items-center justify-center gap-2 transition-all active:scale-98 disabled:opacity-50"
                >
                  <RefreshCw className={`w-3.5 h-3.5 ${isSyncing ? 'animate-spin' : ''}`} />
                  {isSyncing ? 'Syncing with Cloud...' : 'Sync Cloud Backup Now'}
                </button>
              )}
            </div>
          </div>
        )}

        {/* ======================= RESTORE / IMPORT TAB ======================= */}
        {activeTab === 'import' && (
          <div className="space-y-4 animate-fade-in">
            {/* If Restore Succeeded */}
            {restoreSuccess ? (
              <div className="bg-gradient-to-br from-emerald-950/70 to-[#18231C] rounded-3xl p-6 border border-emerald-500/50 text-center space-y-4 shadow-2xl animate-spring-up">
                <div className="w-14 h-14 rounded-full bg-emerald-500/20 text-emerald-400 border border-emerald-500/30 flex items-center justify-center mx-auto shadow-inner">
                  <CheckCircle2 className="w-8 h-8 animate-pulse" />
                </div>
                <div>
                  <h3 className="text-lg font-extrabold text-white">Ledger Restored Successfully!</h3>
                  <p className="text-xs text-gray-300 mt-1">
                    {restoreSuccess.mode === 'replace' 
                      ? 'Full ledger replaced and updated.' 
                      : 'Records merged seamlessly with zero duplicate entries.'}
                  </p>
                </div>

                {user && (
                  <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-emerald-500/20 border border-emerald-500/30 text-emerald-300 text-xs font-bold">
                    <ShieldCheck className="w-4 h-4" />
                    Replicated to Google Cloud
                  </div>
                )}

                <div className="flex gap-2 pt-2">
                  <button
                    onClick={handleResetImport}
                    className="flex-1 py-3 rounded-2xl bg-gray-800 hover:bg-gray-700 text-gray-300 font-bold text-xs transition-all active:scale-95"
                  >
                    Import Another
                  </button>
                  <button
                    onClick={() => { vibrate('light'); onClose(); }}
                    className="flex-1 py-3 rounded-2xl bg-emerald-500 hover:bg-emerald-400 text-black font-black text-xs shadow-lg shadow-emerald-500/30 transition-all active:scale-95"
                  >
                    Done
                  </button>
                </div>
              </div>
            ) : !parsedBackup ? (
              /* Drag and Drop Zone */
              <div className="space-y-3">
                <div
                  onDragOver={(e) => { e.preventDefault(); setDragOver(true); }}
                  onDragLeave={() => setDragOver(false)}
                  onDrop={handleDrop}
                  onClick={() => fileInputRef.current && fileInputRef.current.click()}
                  className={`border-2 border-dashed rounded-3xl p-8 text-center cursor-pointer transition-all duration-300 ${
                    dragOver 
                      ? 'border-emerald-400 bg-emerald-500/10 scale-[1.01]' 
                      : 'border-gray-700/80 hover:border-emerald-500/50 bg-[#252528]/40 hover:bg-[#252528]/70'
                  }`}
                >
                  <input
                    ref={fileInputRef}
                    type="file"
                    accept=".json,application/json"
                    onChange={handleFileSelect}
                    className="hidden"
                  />

                  <div className="w-14 h-14 rounded-2xl bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 flex items-center justify-center mx-auto mb-3 shadow-inner">
                    <UploadCloud className={`w-7 h-7 ${dragOver ? 'animate-bounce' : ''}`} />
                  </div>

                  <h3 className="font-extrabold text-sm text-white mb-1">
                    Drop Cashly Backup JSON Here
                  </h3>
                  <p className="text-xs text-gray-400 max-w-xs mx-auto">
                    Drag & drop your <span className="text-emerald-400 font-bold">.json</span> file here, or <span className="text-emerald-400 font-bold underline">browse files</span>
                  </p>
                  <p className="text-[10px] text-gray-500 mt-3 font-mono">
                    Supports Cashly 3.0 & 2.0 full backups
                  </p>
                </div>

                {fileError && (
                  <div className="bg-rose-500/10 border border-rose-500/30 rounded-2xl p-3 flex items-start gap-2.5 text-rose-300 text-xs animate-fade-in">
                    <AlertTriangle className="w-4 h-4 text-rose-400 flex-shrink-0 mt-0.5" />
                    <span>{fileError}</span>
                  </div>
                )}
              </div>
            ) : (
              /* Backup Preview Sheet */
              <div className="space-y-4 animate-fade-in">
                
                {/* Preview Sheet Card */}
                <div className="bg-[#242426] rounded-3xl p-5 border border-white/10 space-y-4 shadow-xl">
                  <div className="flex items-center justify-between pb-3 border-b border-gray-800">
                    <div className="flex items-center gap-2">
                      <span className="w-2.5 h-2.5 rounded-full bg-emerald-400 animate-pulse" />
                      <h4 className="font-extrabold text-sm text-white">Backup Preview Sheet</h4>
                    </div>
                    <span className="px-2 py-0.5 rounded-full bg-white/10 text-gray-300 text-[10px] font-mono">
                      v{backupAnalysis.version}
                    </span>
                  </div>

                  {/* Summary Details Grid */}
                  <div className="grid grid-cols-2 gap-2.5 text-xs">
                    <div className="bg-black/40 rounded-2xl p-3 border border-white/5">
                      <p className="text-[10px] uppercase font-bold text-gray-400">💼 Accounts</p>
                      <p className="text-base font-extrabold text-white mt-0.5">
                        {backupAnalysis.walletsCount} {backupAnalysis.walletsCount === 1 ? 'account' : 'accounts'}
                      </p>
                    </div>

                    <div className="bg-black/40 rounded-2xl p-3 border border-white/5">
                      <p className="text-[10px] uppercase font-bold text-gray-400">📝 Transactions</p>
                      <p className="text-base font-extrabold text-white mt-0.5">
                        {backupAnalysis.txCount} {backupAnalysis.txCount === 1 ? 'record' : 'records'}
                      </p>
                      <p className="text-[9px] text-gray-400 truncate mt-0.5">
                        {backupAnalysis.dateRange}
                      </p>
                    </div>

                    <div className="bg-black/40 rounded-2xl p-3 border border-white/5">
                      <p className="text-[10px] uppercase font-bold text-gray-400">🎯 Budgets & Goals</p>
                      <p className="text-base font-extrabold text-white mt-0.5">
                        {backupAnalysis.budgetsAndGoalsCount} active
                      </p>
                    </div>

                    <div className="bg-black/40 rounded-2xl p-3 border border-white/5">
                      <p className="text-[10px] uppercase font-bold text-gray-400">💰 Total Money</p>
                      <p className="text-base font-extrabold text-emerald-400 mt-0.5 font-mono">
                        {formatCurrency(backupAnalysis.netWorth, backupAnalysis.currency)}
                      </p>
                    </div>
                  </div>

                  {backupAnalysis.exportedAt && (
                    <p className="text-[10px] text-gray-500 text-center font-mono">
                      Backup Created: {new Date(backupAnalysis.exportedAt).toLocaleString()}
                    </p>
                  )}
                </div>

                {/* Import Mode Radio Selection */}
                <div className="space-y-2">
                  <label className="text-[11px] font-bold text-gray-400 uppercase tracking-wider block px-1">
                    Choose Restore Strategy
                  </label>

                  {/* Mode 1: Smart Merge */}
                  <div
                    onClick={() => { vibrate('light'); setImportMode('merge'); }}
                    className={`p-3.5 rounded-2xl border cursor-pointer transition-all flex items-start gap-3 ${
                      importMode === 'merge'
                        ? 'bg-emerald-500/10 border-emerald-500 shadow-md ring-1 ring-emerald-500/20'
                        : 'bg-[#1C1C1E] border-gray-800 hover:border-gray-700'
                    }`}
                  >
                    <div className={`w-5 h-5 rounded-full border-2 flex items-center justify-center flex-shrink-0 mt-0.5 ${
                      importMode === 'merge' ? 'border-emerald-400 bg-emerald-500 text-black' : 'border-gray-600'
                    }`}>
                      {importMode === 'merge' && <Check className="w-3 h-3 stroke-[3]" />}
                    </div>

                    <div>
                      <div className="flex items-center gap-2">
                        <span className="font-extrabold text-xs text-emerald-400">
                          🟢 Smart Merge (Recommended)
                        </span>
                      </div>
                      <p className="text-[11px] text-gray-300 mt-0.5 leading-relaxed">
                        Combines backup with your current records. Existing data is NEVER deleted; duplicates are automatically skipped.
                      </p>
                    </div>
                  </div>

                  {/* Mode 2: Full Restore */}
                  <div
                    onClick={() => { vibrate('medium'); setImportMode('replace'); }}
                    className={`p-3.5 rounded-2xl border cursor-pointer transition-all flex items-start gap-3 ${
                      importMode === 'replace'
                        ? 'bg-amber-500/10 border-amber-500 shadow-md ring-1 ring-amber-500/20'
                        : 'bg-[#1C1C1E] border-gray-800 hover:border-gray-700'
                    }`}
                  >
                    <div className={`w-5 h-5 rounded-full border-2 flex items-center justify-center flex-shrink-0 mt-0.5 ${
                      importMode === 'replace' ? 'border-amber-400 bg-amber-500 text-black' : 'border-gray-600'
                    }`}>
                      {importMode === 'replace' && <Check className="w-3 h-3 stroke-[3]" />}
                    </div>

                    <div>
                      <div className="flex items-center gap-2">
                        <span className="font-extrabold text-xs text-amber-400">
                          ⚠️ Full Restore (Replace)
                        </span>
                      </div>
                      <p className="text-[11px] text-gray-300 mt-0.5 leading-relaxed">
                        Replaces current ledger completely with this backup.
                      </p>
                    </div>
                  </div>
                </div>

                {/* Cloud Sync notice if signed in */}
                {user && (
                  <p className="text-[11px] text-emerald-400/90 text-center font-medium">
                    ☁️ Cloud sync in progress when you restore...
                  </p>
                )}

                {/* Action Buttons */}
                <div className="flex gap-2 pt-1">
                  <button
                    type="button"
                    onClick={handleResetImport}
                    disabled={isRestoring}
                    className="py-3.5 px-4 rounded-2xl bg-gray-800 hover:bg-gray-700 text-gray-300 font-bold text-xs transition-all active:scale-95 disabled:opacity-50"
                  >
                    Cancel
                  </button>

                  <button
                    type="button"
                    onClick={handleRestoreNow}
                    disabled={isRestoring}
                    className={`flex-1 py-3.5 px-4 rounded-2xl font-black text-xs flex items-center justify-center gap-2 transition-all active:scale-98 shadow-xl ${
                      importMode === 'replace'
                        ? 'bg-amber-500 hover:bg-amber-400 text-black shadow-amber-500/25'
                        : 'bg-emerald-500 hover:bg-emerald-400 text-black shadow-emerald-500/25'
                    } disabled:opacity-50`}
                  >
                    {isRestoring ? (
                      <>
                        <RefreshCw className="w-4 h-4 animate-spin text-black" />
                        <span>{user ? 'Cloud sync in progress...' : 'Restoring Ledger...'}</span>
                      </>
                    ) : (
                      <>
                        <Sparkles className="w-4 h-4 text-black" />
                        <span>Restore Ledger Now</span>
                      </>
                    )}
                  </button>
                </div>
              </div>
            )}
          </div>
        )}

      </div>
    </div>
  );
};
